# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.5
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
      - name: Updating Algolia Index
        run: ALGOLIA_API_KEY='0d12377b218ea5a0ef4e2acd4b518ab1' jekyll algolia
